#!/bin/bash
#set -x

PROJ_NAME=nsdev-daemon
BUILD_DIR=build
SERVICE_NAME=nsdev.service
SERVICE_CFG=nsdev-daemon.cfg
INSTALL_DIR=/lib/systemd/system/
BINARY_FILE=nsdev-daemon
BINARY_INSTALL_DIR=/usr/bin/
CONTROL=control
CHANGELOG=changelog
COPYRIGHT=copyright
VERSION=18.12.0
ROOT_DIR=`pwd`

ARCH=$1

PACKAGE_DIR=$ROOT_DIR/$BUILD_DIR/package-"$ARCH"/$PROJ_NAME
PACKAGE_CTRL_DIR=$PACKAGE_DIR/DEBIAN
PACKAGE_DOC_DIR=$PACKAGE_DIR/usr/share/doc/$PROJ_NAME

#echo PackageDIR=$PACKAGE_DIR
#echo InstallDIR=$PACKAGE_DIR/$INSTALL_DIR

chmod -R 777 $PACKAGE_DIR
rm -rf $PACKAGE_DIR

mkdir -p $PACKAGE_CTRL_DIR
mkdir -p $PACKAGE_DIR/etc
mkdir -p $PACKAGE_DIR/$INSTALL_DIR
mkdir -p $PACKAGE_DIR/$BINARY_INSTALL_DIR
mkdir -p $PACKAGE_DOC_DIR

cp $ROOT_DIR/$CONTROL $PACKAGE_CTRL_DIR/control
cd $PACKAGE_CTRL_DIR/
sed -i "s/NAME/$PROJ_NAME/g" control
sed -i "s/VERSION/$VERSION/g" control
sed -i "s/ARCH/$ARCH/g" control

cp $ROOT_DIR/$SERVICE_CFG $PACKAGE_DIR/etc/
cp $ROOT_DIR/$SERVICE_NAME $PACKAGE_DIR/$INSTALL_DIR
cp $ROOT_DIR/$BINARY_FILE $PACKAGE_DIR/$BINARY_INSTALL_DIR

chmod 755 $PACKAGE_DIR/etc/$SERVICE_CFG
chmod 644 $PACKAGE_DIR/$INSTALL_DIR/$SERVICE_NAME
chmod 755 $PACKAGE_DIR/$BINARY_INSTALL_DIR/$BINARY_FILE

cp $ROOT_DIR/$CHANGELOG $PACKAGE_CTRL_DIR/
gzip -9 -n -f $PACKAGE_CTRL_DIR/changelog
mv $PACKAGE_CTRL_DIR/changelog.gz $PACKAGE_DOC_DIR/changelog.gz

cp $ROOT_DIR/$COPYRIGHT $PACKAGE_DOC_DIR/

echo "/etc/$SERVICE_CFG" > $PACKAGE_CTRL_DIR/conffiles
#echo "$INSTALL_DIR$SERVICE_NAME" >> $PACKAGE_CTRL_DIR/conffiles

cd $ROOT_DIR/$BUILD_DIR/package-"$ARCH"/
fakeroot dpkg-deb -b $PROJ_NAME

#mkdir -p $PACKAGE_DEST_DIR
mv $PROJ_NAME.deb package-"$PROJ_NAME"_"$VERSION"_"$ARCH".deb

lintian package-"$PROJ_NAME"_"$VERSION"_"$ARCH".deb
